name: wg1

channels:
  - defaults
  - conda-forge

dependencies:
  - python=3
  - r-base
  - r-data.table
  - bioconda::bioconductor-deepbluer
  - bioconda::ucsc-bedgraphtobigwig
  - bioconda::ucsc-bigwigtobedgraph
  - bioconda::ucsc-bigwigmerge
  - pandas
  - nodejs
  - flask
  - flask-restful
  - flask-cors
  - bioconda::pybigwig
  - scikit-learn
  - matplotlib
  - kneed
  - r-findpython
  - r-argparse 
  